name: "Run Fluent Updates"
on:
  schedule:
    - cron: "15 9,21 * * *" # 9:15 and 21:15, daily
  workflow_dispatch:

concurrency:
  group: run-fluent-updates
  cancel-in-progress: true

env:
  FLUENT_REPO_AUTH: ${{ secrets.FLUENT_REPO_AUTH }}
  SNITCH_ID: ${{ secrets.SNITCH_ID }}

jobs:
  fluent_processing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: trigger-processing
        shell: bash
        run: ./process-ftl.sh
